require('user/plugins/packer')
require('user/plugins/cmp')
require('user/plugins/lsp')
require('user/plugins/lualine')
require('user/plugins/fzf')
require('user/plugins/treesitter')
require('user/plugins/rust-tools')
